### ISSUE TITLE
MVPs y GDEs

### ISSUE THREAD

**Issue by nbellocam** [lcjury/devs-hispanos#7]
Buenas,

Muy buena lista!. Paso esta info por si la dudas, están los directorios de [MVPs](https://mvp.microsoft.com/en-us/MvpSearch?lo=Argentina%7CUruguay%7CParaguay%7CMexico%7CBolivia%7CChile&sc=e) y [GDEs](https://developers.google.com/community/experts/directory) de los cuales ya hay varios en el listado. Ambos son reconocimientos a referentes de la comunidad por parte de Microsoft y Google respectivamente.

Algunos ejemplos:
- [Leo Pittelli](https://twitter.com/leopittelli)
- [Eva Ferreira](https://twitter.com/evaferreira92)
- [Guillermo Bellmann](https://twitter.com/gjbellmann)
- [Rodrigo Díaz Concha](https://twitter.com/rdiazconcha)
- [Nico Milcoff](https://twitter.com/nmilcoff)
- [Yury Camacho](https://twitter.com/camachoyury)

Y por ultimo, me gustaría aparecer en el listado [Nicolas Bello](https://twitter.com/nbellocam).

Muchas gracias

**Comment by lcjury** [comment]
Muchas gracias por las recomendaciones @nbellocam todos fueron añadidos en https://github.com/lcjury/devs-hispanos/pull/8 :)
